main:
- name: "About"
  pageRef: "about"
  weight: 10
- name: "CV"
  pageRef: "cv"
  weight: 20
- name: "Blog"
  pageRef: "posts"
  weight: 30
- name: "Fiction"
  pageRef: "fiction"
  weight: 40
- name: "Links"
  pageRef: "links"
  weight: 50

footer:
- name: "Tags"
  pageRef: "tags"
  weight: 10
- name: "Categories"
  pageRef: "categories"
  weight: 20
- name: "RSS"
  url: "/feed.xml"
  weight: 30
